# name: "Run isort"

# on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# jobs:
#  build:
#    
#    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#    - name: Set up Python 3.8
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.8
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#        pip install -r requirements_tests.txt
#    - name: run isort
#      run: |
#        isort .

#    - name: Commit changes
#      run: |
#        git config --local user.email "action@github.com"
#        git config --local user.name "GitHub Action"
#        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort'
#      
#    - name: Push changes
#      uses: ad-m/github-push-action@v0.5.0
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}

name: "Run isort"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run isort
      run: |
        pip install isort
        isort .